import { useState, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useNavigate, useParams, Link } from 'react-router-dom';
import { addProduct, editProduct, fetchProduct, clearProduct, clearError } from '../../redux/productSlice';
import { HiArrowLeft, HiSave, HiOutlineCube, HiOutlinePhotograph, HiX, HiCheck, HiOutlineCurrencyDollar, HiViewBoards, HiOutlineCurrencyEuro, HiOutlineCurrencyRupee } from 'react-icons/hi';
import toast from 'react-hot-toast';

const CATEGORIES = [
  'Electronics',
  'Clothing',
  'Home & Kitchen',
  'Books',
  'Sports',
  'Beauty',
  'Toys',
  'Automotive',
  'Other',
];

const ProductForm = () => {
  const { id } = useParams();
  const isEditMode = Boolean(id);
  
  const dispatch = useDispatch();
  const navigate = useNavigate();
  
  const { product, loading, error } = useSelector((state) => state.products);

  const [formData, setFormData] = useState({
    name: '',
    sku: '',
    description: '',
    price: '',
    category: '',
    stock: 0,
    status: 'active',
    imageFile: null,
  });
  const [imagePreview, setImagePreview] = useState('');
  const [skuAutoGenerated, setSkuAutoGenerated] = useState(!isEditMode);

  const [validationErrors, setValidationErrors] = useState({});

  useEffect(() => {
    if (isEditMode) {
      dispatch(fetchProduct(id));
    }
    return () => {
      dispatch(clearProduct());
      dispatch(clearError());
    };
  }, [dispatch, id, isEditMode]);

  useEffect(() => {
    if (isEditMode && product) {
      setFormData({
        name: product.name || '',
        sku: product.sku || '',
        description: product.description || '',
        price: product.price || '',
        category: product.category || '',
        stock: product.stock || 0,
        status: product.status || 'active',
        imageFile: null,
      });
      setImagePreview(product.image?.url || '');
    }
  }, [isEditMode, product]);

  const handleChange = (e) => {
    const { name, value, type } = e.target;
    let finalValue = value;

    if (name === 'sku') {
      finalValue = value.toUpperCase().replace(/\s+/g, '-');
      setSkuAutoGenerated(false);
    }
    if (type === 'number') {
      finalValue = value === '' ? '' : Number(value);
    }

    setFormData(prev => {
      const newData = {
        ...prev,
        [name]: finalValue
      };
      
      // Auto-update status based on stock value
      if (name === 'stock') {
        if (finalValue === 0) {
          newData.status = 'out_of_stock';
        } else if (finalValue > 0 && prev.status === 'out_of_stock') {
          newData.status = 'active';
        }
      }
      
      // Auto-generate SKU
      if (skuAutoGenerated && (name === 'name' || name === 'category')) {
         const catStr = (name === 'category' ? finalValue : newData.category) || 'GEN';
         const nameStr = (name === 'name' ? finalValue : newData.name) || '';
         const catPrefix = catStr.substring(0, 3).toUpperCase();
         const namePrefix = nameStr.toUpperCase().replace(/\s+/g, '-').replace(/[^A-Z0-9-]/g, '').substring(0, 20);
         
         if (namePrefix) {
           newData.sku = `${catPrefix}-${namePrefix}`;
         } else {
           newData.sku = '';
         }
      }
      
      return newData;
    });
    
    if (validationErrors[name]) {
      setValidationErrors(prev => ({ ...prev, [name]: '' }));
    }
  };

  const handleImageChange = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setFormData(prev => ({
      ...prev,
      imageFile: file,
    }));
    setImagePreview(URL.createObjectURL(file));
  };

  const clearSelectedImage = () => {
    setFormData(prev => ({
      ...prev,
      imageFile: null,
    }));
    setImagePreview(product?.image?.url || '');
  };

  const validate = () => {
    const errors = {};
    if (!formData.name.trim()) errors.name = 'Product name is required';
    if (!formData.sku.trim()) errors.sku = 'SKU is required';
    if (!formData.description.trim()) errors.description = 'Description is required';
    if (formData.price === '' || formData.price < 0) errors.price = 'Valid price is required';
    if (!formData.category) errors.category = 'Category is required';
    if (formData.stock === '' || formData.stock < 0) errors.stock = 'Valid stock is required';
    
    setValidationErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!validate()) {
      toast.error('Please fix the errors in the form');
      return;
    }

    try {
      if (isEditMode) {
        await dispatch(editProduct({ id, productData: formData })).unwrap();
      } else {
        await dispatch(addProduct(formData)).unwrap();
      }
      navigate('/admin/products');
    } catch (err) {
      // Error handled in thunk
    }
  };

  return (
    <div className="min-h-screen bg-black pb-20">
      {/* Black Header */}
      <div className="bg-gradient-to-b from-black to-transparent pt-8 pb-12 px-4 border-b border-white/5">
        <div className="mx-auto max-w-5xl">
          <Link to="/admin/products" className="mb-6 inline-flex items-center gap-2 rounded-full bg-[#0a0a0a] px-4 py-2 text-sm font-bold text-zinc-300 shadow-sm border border-white/10 transition-all hover:border-orange-500/30 hover:text-orange-500 hover:-translate-y-0.5">
            <HiArrowLeft /> Back to Inventory
          </Link>
          
          <div className="flex items-center gap-4">
            <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-orange-500 text-3xl text-black shadow-lg shadow-orange-500/30">
              <HiOutlineCube />
            </div>
            <div>
              <h1 className="font-title text-4xl font-black text-white tracking-tight">
                {isEditMode ? 'Edit Product' : 'New Product'}
              </h1>
              <p className="mt-1 text-zinc-400 font-medium text-lg">
                Fill in the details below to update your catalog.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="mx-auto max-w-5xl px-4 -mt-6 relative z-10">
        {error && (
          <div className="mb-6 rounded-2xl border border-red-500/30 bg-red-500/10 p-5 font-bold text-red-400 shadow-sm flex items-center gap-3">
            <HiX className="text-xl"/> {error}
          </div>
        )}

        {loading && isEditMode && !product ? (
          <div className="flex justify-center py-20 bg-[#0a0a0a] rounded-[32px] border border-white/5 shadow-sm">
            <div className="loader"></div>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="bg-[#0a0a0a] rounded-[32px] border border-white/5 shadow-xl shadow-black/50 p-6 md:p-10 space-y-10">
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-10">
              
              {/* Image Upload Area */}
              <div className="md:col-span-2">
                <label className="mb-3 block text-sm font-bold text-zinc-300 uppercase tracking-wider">Product Visual</label>
                <div className="flex flex-col md:flex-row gap-6">
                  <div className="flex h-48 w-48 shrink-0 items-center justify-center overflow-hidden rounded-[24px] border border-white/5 bg-black shadow-inner">
                    {imagePreview ? (
                      <img src={imagePreview} alt="Preview" className="h-full w-full object-cover transition-transform hover:scale-105 duration-500" />
                    ) : (
                      <div className="flex flex-col items-center text-zinc-500">
                        <HiOutlinePhotograph className="text-5xl mb-2 opacity-50" />
                        <span className="text-xs font-bold uppercase">No Image</span>
                      </div>
                    )}
                  </div>
                  <div className="flex flex-1 flex-col justify-center rounded-[24px] border-2 border-dashed border-white/10 bg-black/50 p-6 transition-colors hover:border-orange-500/30 hover:bg-orange-500/5">
                    <input
                      id="product-image"
                      type="file"
                      accept="image/jpeg,image/png,image/gif,image/webp"
                      onChange={handleImageChange}
                      className="sr-only"
                    />
                    <label htmlFor="product-image" className="btn bg-[#0a0a0a] border border-white/10 text-zinc-300 hover:border-orange-500/30 hover:text-orange-500 w-fit cursor-pointer shadow-sm">
                      <HiOutlinePhotograph className="text-lg" />
                      Browse Files
                    </label>
                    <p className="mt-4 text-sm font-medium text-zinc-500">Supports JPEG, PNG, GIF, or WebP (max 5MB).</p>
                    {formData.imageFile && (
                      <button type="button" onClick={clearSelectedImage} className="mt-4 inline-flex w-fit items-center gap-1.5 text-sm font-bold text-red-400 hover:text-red-300 transition-colors">
                        <HiX className="text-base" /> Remove selection
                      </button>
                    )}
                  </div>
                </div>
              </div>

              {/* General Info Section */}
              <div className="md:col-span-2">
                <h3 className="font-title text-xl font-bold text-white border-b border-white/5 pb-3 mb-6">General Information</h3>
              </div>
              
              {/* Name */}
              <div className="form-group md:col-span-2">
                <label className="mb-2 block text-sm font-bold text-zinc-300">Product Name *</label>
                <input 
                  type="text"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  className={`form-control text-lg py-3 rounded-xl bg-black focus:bg-[#0a0a0a] ${validationErrors.name ? 'border-red-500 ring-4 ring-red-500/10' : ''}`}
                  placeholder="e.g. Premium Wireless Headphones"
                />
                {validationErrors.name && <p className="mt-2 text-sm font-bold text-red-500">{validationErrors.name}</p>}
              </div>

              {/* SKU */}
              <div className="form-group">
                <label className="mb-2 block text-sm font-bold text-zinc-300">Stock Keeping Unit (SKU) *</label>
                <input 
                  type="text"
                  name="sku"
                  value={formData.sku}
                  onChange={handleChange}
                  className={`form-control font-mono text-lg uppercase py-3 rounded-xl bg-black focus:bg-[#0a0a0a] ${validationErrors.sku ? 'border-red-500 ring-4 ring-red-500/10' : ''}`}
                  placeholder="WH-001"
                />
                {validationErrors.sku ? (
                   <p className="mt-2 text-sm font-bold text-red-500">{validationErrors.sku}</p>
                ) : (
                   <p className="mt-2 text-xs font-semibold text-zinc-500">Must be unique. Spaces auto-convert to hyphens.</p>
                )}
              </div>

              {/* Category */}
              <div className="form-group">
                <label className="mb-2 block text-sm font-bold text-zinc-300">Category *</label>
                <select 
                  name="category"
                  value={formData.category}
                  onChange={handleChange}
                  className={`form-control text-lg py-3 rounded-xl bg-black focus:bg-[#0a0a0a] ${validationErrors.category ? 'border-red-500 ring-4 ring-red-500/10' : ''}`}
                >
                  <option value="">Select Category...</option>
                  {CATEGORIES.map(cat => <option key={cat} value={cat}>{cat}</option>)}
                </select>
                {validationErrors.category && <p className="mt-2 text-sm font-bold text-red-500">{validationErrors.category}</p>}
              </div>

              {/* Pricing & Inventory Section */}
              <div className="md:col-span-2 mt-4">
                <h3 className="font-title text-xl font-bold text-white border-b border-white/5 pb-3 mb-6">Pricing & Inventory</h3>
              </div>

              {/* Price */}
              <div className="form-group relative">
                <label className="mb-2 block text-sm font-bold text-zinc-300">Price *</label>
                <div className="relative">
                  <HiOutlineCurrencyRupee className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500 text-xl pointer-events-none"/> 
                  <input 
                    type="number"
                    step="0.01"
                    min="0"
                    name="price"
                    value={formData.price}
                    onChange={handleChange}
                    placeholder="0.00"
                    className={`form-price text-lg py-3 rounded-xl bg-black pl-12 focus:bg-[#0a0a0a] ${validationErrors.price ? 'border-red-500 ring-4 ring-red-500/10' : ''}`}
                  />
                </div>
                {validationErrors.price && <p className="mt-2 text-sm font-bold text-red-500">{validationErrors.price}</p>}
              </div>

              {/* Stock */}
              <div className="form-group relative">
                <label className="mb-2 block text-sm font-bold text-zinc-300">Stock Quantity *</label>
                <div className="relative">
                  <HiViewBoards className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500 text-xl z-10 pointer-events-none"/> 
                  <input 
                    type="number"
                    min="0"
                    name="stock"
                    value={formData.stock}
                    onChange={handleChange}
                    className={`form-price text-lg py-3 rounded-xl bg-black focus:bg-[#0a0a0a] ${validationErrors.stock ? 'border-red-500 ring-4 ring-red-500/10' : ''}`}
                    placeholder="0"
                  />
                </div>
                {validationErrors.stock && <p className="mt-2 text-sm font-bold text-red-500">{validationErrors.stock}</p>}
              </div>

              {/* Status */}
              <div className="form-group md:col-span-2">
                <label className="mb-3 block text-sm font-bold text-zinc-300">Visibility Status</label>
                <div className="grid gap-4 sm:grid-cols-3">
                  <label className={`relative cursor-pointer rounded-2xl border-2 p-5 transition-all ${formData.status === 'active' ? 'border-orange-500 bg-orange-500/10 shadow-md shadow-orange-500/10' : 'border-white/10 bg-black hover:border-orange-500/30 hover:bg-orange-500/5'}`}>
                    <input type="radio" name="status" value="active" checked={formData.status === 'active'} onChange={handleChange} className="sr-only" />
                    <div className="flex flex-col items-center text-center">
                      <div className={`mb-2 flex h-8 w-8 items-center justify-center rounded-full ${formData.status === 'active' ? 'bg-orange-500 text-black' : 'bg-[#0a0a0a] text-zinc-500'}`}>
                        <HiCheck className="text-xl" />
                      </div>
                      <span className={`text-sm font-black ${formData.status === 'active' ? 'text-orange-500' : 'text-zinc-400'}`}>Active</span>
                      <span className="mt-1 text-xs font-medium text-zinc-500">Visible to customers</span>
                    </div>
                  </label>

                  <label className={`relative cursor-pointer rounded-2xl border-2 p-5 transition-all ${formData.status === 'inactive' ? 'border-zinc-500 bg-zinc-800 shadow-md' : 'border-white/10 bg-black hover:border-zinc-500/30 hover:bg-zinc-800/50'}`}>
                    <input type="radio" name="status" value="inactive" checked={formData.status === 'inactive'} onChange={handleChange} className="sr-only" />
                    <div className="flex flex-col items-center text-center">
                      <div className={`mb-2 flex h-8 w-8 items-center justify-center rounded-full ${formData.status === 'inactive' ? 'bg-zinc-600 text-white' : 'bg-[#0a0a0a] text-zinc-500'}`}>
                        <HiX className="text-xl" />
                      </div>
                      <span className={`text-sm font-black ${formData.status === 'inactive' ? 'text-white' : 'text-zinc-400'}`}>Inactive</span>
                      <span className="mt-1 text-xs font-medium text-zinc-500">Hidden from catalog</span>
                    </div>
                  </label>

                  <label className={`relative cursor-pointer rounded-2xl border-2 p-5 transition-all ${formData.status === 'out_of_stock' ? 'border-red-500/50 bg-red-500/10 shadow-md shadow-red-500/10' : 'border-white/10 bg-black hover:border-red-500/30 hover:bg-red-500/5'}`}>
                    <input type="radio" name="status" value="out_of_stock" checked={formData.status === 'out_of_stock'} onChange={handleChange} className="sr-only" />
                    <div className="flex flex-col items-center text-center">
                      <div className={`mb-2 flex h-8 w-8 items-center justify-center rounded-full ${formData.status === 'out_of_stock' ? 'bg-red-500 text-white' : 'bg-[#0a0a0a] text-zinc-500'}`}>
                        <HiOutlineCube className="text-xl" />
                      </div>
                      <span className={`text-sm font-black ${formData.status === 'out_of_stock' ? 'text-red-400' : 'text-zinc-400'}`}>Out of Stock</span>
                      <span className="mt-1 text-xs font-medium text-zinc-500">Visible but unpurchasable</span>
                    </div>
                  </label>
                </div>
              </div>

              {/* Description Section */}
              <div className="md:col-span-2 mt-4">
                <h3 className="font-title text-xl font-bold text-white border-b border-white/5 pb-3 mb-6">Additional Details</h3>
              </div>

              {/* Description */}
              <div className="form-group md:col-span-2">
                <label className="mb-2 block text-sm font-bold text-zinc-300">Detailed Description *</label>
                <textarea 
                  name="description"
                  value={formData.description}
                  onChange={handleChange}
                  rows="5"
                  className={`form-control text-base py-4 rounded-[16px] bg-black focus:bg-[#0a0a0a] ${validationErrors.description ? 'border-red-500 ring-4 ring-red-500/10' : ''}`}
                  placeholder="Describe the product's features, dimensions, materials, etc..."
                ></textarea>
                {validationErrors.description && <p className="mt-2 text-sm font-bold text-red-500">{validationErrors.description}</p>}
              </div>

            </div>

            {/* Action Buttons */}
            <div className="mt-10 flex items-center justify-end gap-4 rounded-[24px] bg-black p-6 border border-white/5">
              <Link to="/admin/products" className="btn bg-[#0a0a0a] border border-white/10 text-zinc-300 hover:bg-[#0a0a0a] hover:text-white hover:border-white/30 px-6 py-3 rounded-xl font-bold text-base">
                Cancel
              </Link>
              <button 
                type="submit" 
                className="btn btn-primary px-8 py-3 rounded-xl font-bold text-base shadow-lg shadow-orange-500/30 flex items-center gap-2"
                disabled={loading}
              >
                {loading ? <div className="w-5 h-5 border-2 border-black/30 border-t-black rounded-full animate-spin"></div> : <HiSave className="text-xl" />}
                {isEditMode ? 'Save Changes' : 'Publish Product'}
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
};

export default ProductForm;
